In [9]:
import pandas as pd
import numpy as np
print("pandas version",pd.__version__)

pandas version 3.0.1

In [10]:
# create series
s1=pd.Series([1,2,3,4,5])
s1
#by default list ka undex hota hi write naii karna prta
s2 = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
print(s2)
s2=pd.Series([1,4,7,2,8,2] , index=[0,1,2,3,4,5])
print(s2)

a    1
b    2
c    3
d    4
e    5
dtype: int64
0    1
1    4
2    7
3    2
4    8
5    2
dtype: int64

In [11]:
#combine keys or value
s2=pd.Series({1:0,2:1,3:2,4:3,5:4})
s2
print(s2.index)
print(s2.values)
print(s2.dtype)

RangeIndex(start=1, stop=6, step=1)
[0 1 2 3 4]
int64

In [12]:
p1=pd.DataFrame([
    {'Name':'Alice',"Age":26,'City':'New year'},
     {'Name':'Bob',"Age":26,'City':'paris'}])
print(p1)

p2=pd.DataFrame({'Name':['ali','ahmad','zain','majid'],'age':[23,16,16,26]})
p2

    Name  Age      City
0  Alice   26  New year
1    Bob   26     paris

    Name  age
0    ali   23
1  ahmad   16
2   zain   16
3  majid   26

In [13]:
s2=pd.Series({'Narnia':2013,'harry potter':2003,'stanger things':2000,'alice in the boraderlands':2019})
print(s2)

Narnia                       2013
harry potter                 2003
stanger things               2000
alice in the boraderlands    2019
dtype: int64

In [14]:
#p1=pd.DataFrame(np.random.randint(1,100,50),column=["values"])
#print(p1)


df = pd.DataFrame(np.random.randint(1,100,50), columns=["Values"])
print(df)

    Values
0       24
1       42
2       47
3       56
4       23
5        2
6       96
7       86
8       78
9       51
10       4
11      63
12      57
13      46
14      78
15      67
16      88
17      63
18       5
19      11
20      35
21      50
22      14
23      59
24      63
25      88
26      10
27      81
28      75
29      60
30      68
31      52
32      94
33      79
34      31
35      77
36       8
37      62
38      84
39      64
40      99
41      88
42      58
43      23
44      71
45      24
46      92
47      87
48      26
49      14

In [15]:
data = np.random.randint(1,100,50)     # 50 random values
index = np.random.randint(1,100,50)  # 50 random index

df = pd.DataFrame(data, index=index, columns=["Values"])

print(df)

    Values
19      56
49       1
13      44
59      84
71      48
7       11
28      62
63      97
23      95
53      10
5       10
73      63
33      73
51      53
62      91
84      16
50      59
15      71
32      97
47      88
57      26
32      85
27      74
40      10
7       55
24      22
92       6
66      71
18       2
23      90
81      11
99      77
43      34
21      41
5       43
65      55
82      89
84      17
34      75
86      19
35      46
1       28
94      22
2       83
14      15
43      22
80      97
47      46
39      80
14      65

In [16]:
import numpy as np
import pandas as pd
df1=pd.DataFrame(np.random.randn(20,3),
                 columns=['a','b','c'],
                 index=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(df1)

           a         b         c
1   0.316185 -0.717194  0.819594
2  -1.557059  1.440629  0.784818
3   0.000190 -0.508344 -2.713398
4   1.559203 -1.024161  2.095381
5  -1.057699  0.929202 -0.999499
6   0.178019  0.354458  0.051232
7  -0.498646 -0.569757 -0.398812
8  -0.185726 -0.548003 -0.841578
9  -0.590777 -1.225204  0.366156
10  1.689346  1.963007 -0.982852
11  1.175283 -0.117416 -0.758838
12  0.348743 -0.853759 -0.451985
13  0.621945 -0.929073 -0.745742
14 -0.703645  0.369336  0.862823
15 -0.035546  0.866200  1.808234
16  0.442044 -0.410788 -0.775761
17 -0.848417  0.926510 -0.025013
18 -0.507146  0.601039 -0.347186
19  0.328345  0.689968  0.666234
20 -0.076443 -0.846042  0.504461

In [17]:
f2 = pd.DataFrame([
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'Paris'},
    {'Name' :'hamza','Age':34,'City':'gujranwala'}])
print(f2)
#print(f2.shape)
#print(f2.info())
#f2.describe() #numerical data py kam krta hai,quick statistical view provide krta hai
print(f2.iloc[1:2])

    Name  Age        City
0  Alice   25    New York
1    Bob   30       Paris
2  hamza   34  gujranwala
  Name  Age   City
1  Bob   30  Paris

In [18]:
#csv-CSV ek simple text file hoti hai jisme table jaisa data commas se separate hota hai.
from io import StringIO
df2=StringIO("Name,Sallary,Age \n Majida, 445632,21\n Tasneem,223242,20 ")
data=pd.read_csv(df2)
print(data)

       Name  Sallary  Age
0    Majida   445632    21
1   Tasneem   223242    20

In [19]:
x=[4,6,8,2,1,13,14]
s=pd.Series(x,index=('a','b','c','d','e','f','g'), name="my data")
s['d']

np.int64(2)

In [20]:
dept=pd.DataFrame({'Name':['fatima','hamza','wajiha','ali','hafsa','maham','shehriyar','haris','huda','ahsan'],
'Age':[21,23,34,43,33,24,25,27,20,30],'Salary':[40000,34000,54000,40000,50000,67000,87000,45000,55000,60000],
'Department':['IT','HR','TECH','IT','HR','FINANCE','FINANCE','HR','IT','IT']})
#NAME and salary for all rows
#print(dept)
#print(dept[['Name','Salary']])
#print(dept.loc[: , 'Name'])
#print(dept[(dept['Department'] =='IT') & (dept['Age']>30)])
#print(dept['Department'].nunique())
#print(dept['Department'].nunique())
#print(dept['Department'].value_counts())
#print(dept['Age'].value_counts())
#age=dept.sort_values('Age')
#print(age)
dept_map={'IT':'INFORMATON TECH','HR':'HUMAN RESOURCE'}
dept['dept_full'] = dept['Department'].map(dept_map)
dept

        Name  Age  Salary Department        dept_full
0     fatima   21   40000         IT  INFORMATON TECH
1      hamza   23   34000         HR   HUMAN RESOURCE
2     wajiha   34   54000       TECH              NaN
3        ali   43   40000         IT  INFORMATON TECH
4      hafsa   33   50000         HR   HUMAN RESOURCE
5      maham   24   67000    FINANCE              NaN
6  shehriyar   25   87000    FINANCE              NaN
7      haris   27   45000         HR   HUMAN RESOURCE
8       huda   20   55000         IT  INFORMATON TECH
9      ahsan   30   60000         IT  INFORMATON TECH